name: Make videos
on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
    secrets:
      nara-token:
        required: true
      gith-token:
        required: true
jobs:
  make_video:
    runs-on: ubuntu-latest
    steps:
    - uses: narakeet/build-video-github-action@v1.0.2
      id: video
      with:
        source-path: ${{ inputs.domain }}/script/source.md
        github-token: ${{ secrets.gith-token }}
        api-key: ${{ secrets.nara-token }}
    - uses: actions/upload-artifact@v1
      with:
        name: video
        path: "${{ steps.video.outputs.video-file }}"
    - uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: "${{ steps.video.outputs.video-file }}"
        GITHUB_TOKEN: ${{ secrets.gith-token }}
